### PR TITLE
Allow sync mode to be snap sync.

### LINKED ISSUE #94: Default sync mode set to fast sync. Snap sync is much faster should be new default.
**Is your feature request related to a problem? Please describe.**
Nethermind takes a long time to sync in Fast sync mode which is the default setting right now despite snapshot sync being released a long time now and it's much faster. 

**Describe the solution you'd like**
Change default sync mode to snap

### PR DESCRIPTION
**Pull request by alexpeterson91**
allow sync mode to be snap sync for 10x faster sync times

Must be tested due to possible issues with already synced clients
_Update: no isssues found with clearing DB or not after months of testing_
Reference:
https://docs.nethermind.io/nethermind/ethereum-client/sync-modes#snap-sync

_Changed to Allow Snap Sync Via Advanced mode/advanced editor, doesnt change default setting_

Fixes #94

### CODE REVIEW

**Comment by tropicar** [comment]
I have tested this way of syncing in a synced nethermind node and I had no problem.

**Comment by alexpeterson91** [comment]
Yes I have a link to those docs and mentioned this in the linked issue. I guess I wanna see what happens if I upgrade to it being snap sync while synced will actually do. The CI is not publishing a IPFS hash to test. Build is taking like 20s only. Is there something up with the workflow on this repo?

**Review by 3alpha — APPROVED** [review]
In principle this is fine, but testing is needed.

**Comment by alexpeterson91** [comment]
It’s been tested for months just not widely should be made default if there’s no db but not if not. probably more than we think since a bunch of users do custom Configs which I didn’t think was ever common and is a bad idea here for mainnet. Especially as repo client. Sent from my iPhoneOn Oct 27, 2022, at 2:02 PM, 3alpha ***@***.***> wrote:﻿
@3alpha approved this pull request.

In principle this is fine, but testing is needed.

**Comment by alexpeterson91** [comment]
> In principle this is fine, but testing is needed.

Forgot to add selection to advanced setup wizard. Will need another review shortly.

**Pull request merged**
